name: Linter
on: pull_request
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: xt0rted/markdownlint-problem-matcher@v2
            - name: "Run Markdown linter"
              uses: docker://avtodev/markdown-lint:v1
              with:
                  args: docs/**/*.md
